---

- name: Install uv using standalone installer
  become: yes
  become_user: "{{ app_user }}"
  shell:
    cmd: curl -LsSf https://astral.sh/uv/install.sh | sh
    chdir: "{{ ansible_env.HOME }}"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/uv"
  environment:
    UV_INSTALL_DIR: "{{ ansible_env.HOME }}/.local/bin"
