$ANSIBLE_VAULT;1.1;AES256
65356236613637626436363564323464343733636537653530663135633166303664613432643533
3537376265633333373933386535636261336162623262610a363362343236303564363561316638
63666566323635353332623037663138396361366566373033636264386434376635643139346131
6634656261393931390a326634626361333762366235626436306237623634353735393965316436
32656364666265373837643366353661326538316532376231366536336363636361313935373634
37633661386639306565633865623237663661366134646130366163363231363739336631636435
62363333623635383564616639316339623436393164313061353565616236363037316263646436
61376632343335633137326634643261623763663138316535666436313635656561313636366632
32313535633730383736376365363131333464383432653561376532303666383463373865306166
61653366373663656563643537646336313435636537613639393365646538633266633962633564
32616132626335386264336637633938373366663361373565373463616634326230616433336464
37306562353738336131333064373166366539613038623866396163376338643135623038646639
30376463666139623835373761623165363466633766393639393363333433646330383935376439
39643366313038313134346464363738303462306136303766623364616539326436626431393737
39353033326131656132633837663361643535343631636334613361666365353630303464663632
33643165346237616264326632646232656461633733383863326139343634633033623238623763
38303332653633393730373838386161663432353338666339343962616539343163
